### ISSUE TITLE
Codecov randomly fails the build due to inability to upload the results

### ISSUE THREAD

**Issue by rakvium** [rakvium/blog#152]
`Build and test with Rake` step fails even though there is no failed tests due to `exit 1` on unsuccessful upload to Codecov, see https://github.com/rakvium/blog/actions/runs/8965641702/job/24619519961:

```
Finished in 2.09 seconds (files took 4.1 seconds to load)
141 examples, 0 failures

Randomized with seed 34381


  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _\`|/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                               Ruby-0.2.12
==> GitHub Actions detected
==> Appending file network
==> Gzipping contents
==> Uploading reports
    url:   https://codecov.io/
    query: token=secret&flags&package=ruby-0.2.12&service=github-actions&branch=&slug=rakvium%2Fblog&build=8965588509&commit=cbe16ddaf939b98350c87ea35689be9ecf35dce9
->  Pinging Codecov
https://codecov.io/upload/v4?token=secret&flags&package=ruby-0.2.12&service=github-actions&branch=&slug=rakvium%2Fblog&build=8965588509&commit=cbe16ddaf939b98350c87ea35689be9ecf35dce9
/opt/hostedtoolcache/Ruby/3.0.6/x64/lib/ruby/3.0.0/uri/common.rb:676:in `URI': bad argument (expected URI object or URI string) (ArgumentError)
	from /opt/hostedtoolcache/Ruby/3.0.6/x64/lib/ruby/gems/3.0.0/gems/codecov-0.2.12/lib/codecov.rb:409:in `upload_to_v4'
	from /opt/hostedtoolcache/Ruby/3.0.6/x64/lib/ruby/gems/3.0.0/gems/codecov-0.2.12/lib/codecov.rb:375:in `upload_to_codecov'
	from /opt/hostedtoolcache/Ruby/3.0.6/x64/lib/ruby/gems/3.0.0/gems/codecov-0.2.12/lib/codecov.rb:473:in `format'
	from /opt/hostedtoolcache/Ruby/3.0.6/x64/lib/ruby/gems/3.0.0/gems/simplecov-0.13.0/lib/simplecov/result.rb:47:in `format!'
	from /opt/hostedtoolcache/Ruby/3.0.6/x64/lib/ruby/gems/3.0.0/gems/simplecov-0.13.0/lib/simplecov/configuration.rb:172:in `block in at_exit'
	from /opt/hostedtoolcache/Ruby/3.0.6/x64/lib/ruby/gems/3.0.0/gems/simplecov-0.13.0/lib/simplecov/defaults.rb:67:in `block in <top (required)>'
->  Uploading to

/opt/hostedtoolcache/Ruby/3.0.6/x64/bin/ruby -I/opt/hostedtoolcache/Ruby/3.0.6/x64/lib/ruby/gems/3.0.0/gems/rspec-core-3.9.3/lib:/opt/hostedtoolcache/Ruby/3.0.6/x64/lib/ruby/gems/3.0.0/gems/rspec-support-3.9.3/lib /opt/hostedtoolcache/Ruby/3.0.6/x64/lib/ruby/gems/3.0.0/gems/rspec-core-3.9.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
Error: Process completed with exit code 1.
```

---

Possible solutions:
- move from https://github.com/codecov/codecov-ruby, which is deprecated, to https://github.com/dashingrocket/simplecov-cobertura (replace `codecov` with `simplecov-cobertura` and `SimpleCov::Formatter::Codecov` with `SimpleCov::Formatter::CoberturaFormatter` as per the [migration guide](https://docs.codecov.com/docs/deprecated-uploader-migration-guide#ruby-uploader))
- consider removing `codecov` from the project completely to rely on fewer less third-party services and avoid similar issues in the future

**Comment by rakvium** [comment]
I would prefer removing `codecov` from the project completely for now so the bills with the passing tests not [fail just because of the deprecated gem malfunction](https://github.com/rakvium/blog/pull/123#issuecomment-2375190865).
